# Numpy Array

In [5]:
import numpy as np
number_list = list(range(10))
number_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
array_numpy = np.array(number_list)
array_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([1,3,4,2.5])

array([1. , 3. , 4. , 2.5])

In [10]:
np.array([3.4, 'pp4rs'])

array(['3.4', 'pp4rs'], dtype='<U32')

In [12]:
np.array([1.2,3.4, 3.6], dtype='complex')

array([1.2+0.j, 3.4+0.j, 3.6+0.j])

In [14]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.arange(0,20,0.2)
np.linspace(0,20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.random.random(5)

array([0.35861541, 0.38061614, 0.09207499, 0.52356508, 0.6450355 ])

In [26]:
np.random.seed(42)
np.random.normal(loc=1 , scale=3, size=100)

array([ 2.49014246,  0.5852071 ,  2.94306561,  5.56908957,  0.29753988,
        0.29758913,  5.73763845,  3.30230419, -0.40842316,  2.62768013,
       -0.39025308, -0.39718926,  1.72588681, -4.73984073, -4.1747535 ,
       -0.68686259, -2.03849336,  1.942742  , -1.72407223, -3.2369111 ,
        5.39694631,  0.3226711 ,  1.20258461, -3.27424456, -0.63314817,
        1.33276777, -2.45298073,  2.12709406, -0.80191607,  0.12491875,
       -0.80511984,  6.55683455,  0.95950833, -2.17313279,  3.46763474,
       -2.66253095,  1.62659079, -4.87901037, -2.98455815,  1.59058371,
        3.21539974,  1.51410484,  0.65305515,  0.09668891, -3.43556597,
       -1.15953263, -0.38191631,  4.17136668,  2.03085487, -4.28912047,
        1.97225191, -0.15524684, -1.030766  ,  2.83502887,  4.09299857,
        3.79384036, -1.51765257,  0.07236287,  1.99379029,  3.92663538,
       -0.43752271,  0.44302307, -2.31900492, -2.58861987,  3.43757747,
        5.06872009,  0.78396964,  4.01059869,  2.08490808, -0.93

In [29]:
np.random.randint(0, 10, (3,3))

array([[8, 4, 0],
       [2, 9, 7],
       [5, 7, 8]])

In [32]:
np.random.seed(420)
a = np.random.normal(loc=5, scale=3, size=(3,6))
a

array([[ 3.54382744, -0.71546154,  3.42133461,  4.05936194,  5.99211948,
         7.81561174],
       [ 3.29536651,  4.4186742 ,  8.93841453, 10.04375299,  2.69559216,
         2.71064617],
       [ 3.62787366, -1.46624955,  6.54550841,  6.13762885,  2.90019885,
         7.12677171]])

In [34]:
b = np.array(a, dtype='int')
b

array([[ 3,  0,  3,  4,  5,  7],
       [ 3,  4,  8, 10,  2,  2],
       [ 3, -1,  6,  6,  2,  7]])

In [40]:
a.ndim
np.array([1,2,3,4]).shape
a.size

18

In [42]:
a.dtype
b.dtype

dtype('int64')

In [43]:
2**32

4294967296

In [52]:
b.astype('int8').nbytes

18

In [57]:
b

array([[ 3,  0,  3,  4,  5,  7],
       [ 3,  4,  8, 10,  2,  2],
       [ 3, -1,  6,  6,  2,  7]])

In [61]:
b[:,3]

array([ 4, 10,  6])

In [62]:
b[1,:]

array([ 3,  4,  8, 10,  2,  2])

In [68]:
try:
    b[7,8]
except IndexError:
    b[1,1]

In [76]:
c = np.array(range(27)).reshape((3,3,3))
c.shape

(3, 3, 3)

In [77]:
b

array([[ 3,  0,  3,  4,  5,  7],
       [ 3,  4,  8, 10,  2,  2],
       [ 3, -1,  6,  6,  2,  7]])

In [78]:
b[0,1] = 1

In [84]:
b[:,2] = np.array([3,3,3])
b

array([[ 3,  1,  3,  4,  5,  7],
       [ 3,  4,  3, 10,  2,  2],
       [ 3, -1,  3,  6,  2,  7]])

In [93]:
a = np.random.normal(size=(4,3))
a

array([[-0.18399315, -0.11036458, -1.22169663],
       [ 0.36689353,  0.06448467, -1.50476116],
       [-0.75351004, -1.304025  , -1.20345087],
       [ 0.01389041, -1.2885408 ,  0.33479633]])

In [101]:
b

array([[10,  1,  3,  4,  5,  7],
       [ 3,  4,  3, 10,  2,  2],
       [ 3, -1,  3,  6,  2,  7]])

In [104]:
c=b.copy()
c[0,0]= 30
c

array([[30,  1,  3,  4,  5,  7],
       [ 3,  4,  3, 10,  2,  2],
       [ 3, -1,  3,  6,  2,  7]])

In [110]:
c

array([[ 1,  1,  3,  4,  5,  7],
       [ 3,  4,  3, 10,  2,  2],
       [ 3, -1,  3,  6,  2,  7]])

In [107]:
a = c[:,0].copy()
a

array([30,  3,  3])

In [111]:
# concatenate
c

array([[ 1,  1,  3,  4,  5,  7],
       [ 3,  4,  3, 10,  2,  2],
       [ 3, -1,  3,  6,  2,  7]])

In [133]:
a = c[:,0]
b = c[:,1]
b.shape

(3,)

In [134]:
b=b[:, np.newaxis]
a=a[:, np.newaxis]

In [137]:
np.concatenate([a,b], axis=0)

array([[ 1],
       [ 3],
       [ 3],
       [ 1],
       [ 4],
       [-1]])

In [146]:
a = (1,2)
c[a,(0,1)]

array([ 3, -1])

# Numpy vs loops

In [148]:
np.random.seed(42)
def calc_inverse(values):
    output = np.zeros(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, 10)
calc_inverse(values)

array([0.14285714, 0.25      , 0.125     , 0.2       , 0.14285714,
       0.33333333, 0.14285714, 0.125     , 0.2       , 0.25      ])

In [149]:
n = 10**6
many_numbers = np.random.randint(1,10,n)
%timeit calc_inverse(many_numbers)

981 ms ± 5.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [151]:
%timeit 1.0/many_numbers

853 µs ± 27.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [174]:
values.astype(np.float64)
values ** 500

array([ 5324721688969341921,                    0,                    0,
       -2947007275342514511,  5324721688969341921, -3526474796859007727,
        5324721688969341921,                    0, -2947007275342514511,
                          0])

In [178]:
values = values.reshape(2,5)

In [179]:
values

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4]])

In [185]:
np.mean(values, axis=0)

array([5. , 5.5, 8. , 5. , 5.5])

In [188]:
np.sum(values, axis=0).shape

(5,)

In [189]:
-(values + 5)**2 - np.log(10)

array([[-146.30258509,  -83.30258509, -171.30258509, -102.30258509,
        -146.30258509],
       [ -66.30258509, -146.30258509, -171.30258509, -102.30258509,
         -83.30258509]])

# Boolean Indexing

In [190]:
values

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4]])

In [198]:
np.mean(values >= 5)

0.7

In [199]:
indexing_values = values >= 5
values[indexing_values]

array([7, 8, 5, 7, 7, 8, 5])

In [200]:
indexing_values

array([[ True, False,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [194]:
np.std(values, axis=0)

array([2. , 1.5, 0. , 0. , 1.5])

In [201]:
values

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4]])

In [223]:
index_values = (values>3) & (values<5) # and
values[index_values]

array([4, 4])

In [224]:
index_values = (values>3) | (values<5) # or
values[index_values]

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4])

In [203]:
index_values

array([[False,  True, False, False, False],
       [False, False, False, False,  True]])

In [214]:
all(values>0) and all(values<100)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [222]:
np.any(values<5, axis=0)

array([ True,  True, False, False,  True])

In [225]:
values

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4]])

In [219]:
[values<5]

array([[False,  True, False, False, False],
       [ True, False, False, False,  True]])

In [235]:
number_list = [2,3,4]
inis = np.isin(values, number_list)
inis

array([[False,  True, False, False, False],
       [ True, False, False, False,  True]])

In [234]:
where_is = np.where(inis)
where_is

(array([0, 1, 1]), array([1, 0, 4]))

In [233]:
values[where_is]

array([4, 3, 4])

In [236]:
np.unique(values[where_is])

array([3, 4])

In [237]:
set(values[where_is])

{3, 4}

In [238]:
values

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4]])

In [241]:
np.sort(values, axis=0)

array([[3, 4, 8, 5, 4],
       [7, 7, 8, 5, 7]])

# OLS

In [248]:
# generate Data
n_obs = 1000
n_dim = 5
beta = np.array([1,0,1,0,1])

X = np.random.normal(size=(n_obs, n_dim))
y = X.dot(beta) + np.random.normal(size=(n_obs))

In [250]:
X.shape

(1000, 5)

In [252]:
def compute_ols(X, y , constant_add=True):
    if constant_add:
        constant = np.ones((len(X), 1))
        X = np.column_stack([constant, X])

    XX = X.T @ (X)
    XX_inv = np.linalg.inv(XX)
    Xy = X.T @ (y)
    beta = XX_inv @ (Xy)

    return beta

compute_ols(X, y)
compute_ols(X, y, True)
compute_ols(X, y, False)

array([ 1.02277634, -0.03858539,  0.99199747, -0.02745278,  0.98473842])

In [ ]:
np.linalg.inv
X.T